services:
  service:
    image: ghcr.io/nijeti/cinema-keeper/service:${VERSION-latest}
    restart: unless-stopped
    networks:
      - network
    ports:
      - 8080:8080
    
  db:
    image: ghcr.io/nijeti/cinema-keeper/db:1
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:

networks:
  network:
