services:
  service:
    image: ghcr.io/nijeti/cinema-keeper-service:${VERSION-latest}
    restart: unless-stopped
    depends_on:
      migrator:
        condition: service_completed_successfully
    environment:
      DISCORD__TOKEN: ${SERVICE_DISCORD_TOKEN}
      DB__CONNECTION_STRING: ${DB_CONNECTION_STRING}
    networks:
      - network
    
  db:
    image: ghcr.io/nijeti/cinema-keeper-db:${VERSION-latest}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - network
    volumes:
      - db:/var/lib/postgresql/data
  
  migrator:
    image: ghcr.io/nijeti/cinema-keeper-migrator:${VERSION-latest}
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB__CONNECTION_STRING: ${DB_CONNECTION_STRING}
    networks:
      - network

volumes:
  db:

networks:
  network:
