services:
  service:
    image: ghcr.io/nijeti/cinema-keeper-service:${VERSION-latest}
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SERVICE_DISCORD_TOKEN: ${SERVICE_DISCORD_TOKEN}
      SERVICE_DB_CONNECTION_STRING: ${SERVICE_DB_CONNECTION_STRING}
    networks:
      - network
    volumes:
      - ./config.yaml:/app/config.yaml
    
  db:
    image: ghcr.io/nijeti/cinema-keeper-db:${VERSION-latest}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - network
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:

networks:
  network:
