services:
  service:
    profiles:
      - donotstart

  db:
    image: !reset null
    build:
      dockerfile: ./build/db/Dockerfile
      context: .
    ports:
      - 5432:5432

  migrator:
    image: !reset null
    build:
      dockerfile: ./build/migrator/Dockerfile
      context: .
