name: 'Build service'

on:
  push:
    tags:
      - 'v*.*.*'

env:
  IMAGE: 'ghcr.io/nijeti/cinema-keeper/service'
  DOCKERFILE: 'build/service/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Extract meta'
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: 'Login to container registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push'
        uses: docker/build-push-action@v5
        with:
          file: ${{ env.DOCKERFILE }}
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          push: true
