name: 'Release'

on:
  push:
    tags:
      - 'v*.*.*'

env:
  MIGRATOR_IMAGE: 'ghcr.io/nijeti/cinema-keeper-migrator'
  MIGRATOR_DOCKERFILE: 'build/migrator/Dockerfile'
  
  SERVICE_IMAGE: 'ghcr.io/nijeti/cinema-keeper-service'
  SERVICE_DOCKERFILE: 'build/service/Dockerfile'

jobs:
  build-migrator:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Login to container registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Extract meta'
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.MIGRATOR_IMAGE }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}    

      - name: 'Build and push'
        uses: docker/build-push-action@v5
        with:
          file: ${{ env.MIGRATOR_DOCKERFILE }}
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          push: true
  
  build-service:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Login to container registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Extract meta'
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.SERVICE_IMAGE }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}    

      - name: 'Build and push'
        uses: docker/build-push-action@v5
        with:
          file: ${{ env.SERVICE_DOCKERFILE }}
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          push: true

  deploy:
    runs-on: ubuntu-latest

    needs:
      - build-migrator
      - build-service

    environment:
      name: prod

    permissions:
      contents: read
      packages: read

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Calculate version'
        run:
          VERSION=${GITHUB_REF_NAME#v}
          echo Deploying version $VERSION
          echo 'VERSION=$VERSION' >> $GITHUB_ENV

      - name: 'Login to container registry'
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker login \
              -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} \
              ghcr.io

      - name: 'Copy docker-compose.yaml'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: docker-compose.yaml
          target: ${{ secrets.PATH }}

      - name: 'Run containers from docker-compose.yaml'
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PATH }}
            VERSION=$VERSION docker compose up -d
