name: 'Validate'

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'cmd/**'
      - 'internal/**'

env:
  SERVICE: 'cmd/service/main.go'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Go'
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: 'Vet'
        run: go vet ./...

      - name: 'Install dependencies'
        run: go mod download

      - name: 'Build'
        run: go build ${{ env.SERVICE }}

      - name: 'Test'
        run: go test -v ./...
